version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.17
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build:
    jobs:
      - build-and-test
